feat: add linter and fix errors

diff --git a/lint b/lint
--- a/lint
+++ b/lint
@@ -3,11 +3,14 @@ require() {
   hash "$@" || exit 127
 }
 require sqlfluff
-sqlfluff fix --dialect sqlite -- *.sql
 rm -f lint.out
-sqlfluff lint --dialect sqlite -- *.sql &> lint.out
+sqlfluff fix --dialect sqlite -- *.sql
 declare -i exitcode=$?
 if [[ $exitcode != 0 ]]; then
-  echo "Errors found. Check lint.out"
+  sqlfluff lint --dialect sqlite -- *.sql &> lint.out
+  exitcode=$?
+  if [[ $exitcode != 0 ]]; then
+    echo "Errors found. Check lint.out"
+  fi
 fi
 exit "$exitcode"
